[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "d2dad4eed2d04f95f304c6c7ef0f7de5df10fba7"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"