[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "65d57b982485bcdf191a104cdbc24f77db637e59"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"