[workspace]
members = [
    "test-app",
    "voxel-engine",
]
resolver = "2" # required for wgpu to compile

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "1116207f7dbcc04fbcfd10eecc09e3988a4c726a"}