[workspace]
edition = "2021"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "483f2464a82a437248c92eb3169bfa5c6485cd8e"}