[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "b22db47e1003db2d712baec46c0f0a1f88b0a837"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"