[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "6f56380826ce4641fccb672c92f5c97601041f4c"}

[profile.release]
opt-level = 2
overflow-checks = false
# lto = "thin"