[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "756fb069b10c14bf06cc4ab07d0fce1e80fc559d"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"