[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "32a5c7db3535250c43738e3da5877497b1274960"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"