[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "4852fc7578b7a55db4c05a6fb9f8ebdd290571e1"}

[profile.release]
opt-level = 2
overflow-checks = false
# lto = "thin"