[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "4b1865f8bda3c3d6b3f399fb6727635b3ffcbb41"}

[profile.release]
opt-level = 2
overflow-checks = false
# lto = "thin"