[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "d3e41e2ff7653bd726854cd0a36e146e517a6b7c"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"