[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "0e9f6e92ea509c1a285d8c85a828674f5ed32b84"}

[profile.release]
opt-level = 2
overflow-checks = false
# lto = "thin"