[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "3628e09045923ac6e58379c236ed0300491871e4"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"