[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "fb5588413f9438592ebf81cc2820408ffcdcb759"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"