[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "0eeb8f95fbb05ffbf705d8da4bd3f1b104065645"}

[profile.release]
opt-level = 2
overflow-checks = false
# lto = "thin"