[workspace]
edition = "2021"
resolver = "2"
members = [
    "test-app",
    "voxel-engine",
]

[workspace.dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "f8cbc735ba699604ffa2293c368701370c92ab6d"}

[profile.release]
opt-level = 3
overflow-checks = false
# lto = "thin"