[package]
name = "voxel-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "546f7fc194e9435eb177035fe67a030db4091f1b"}
downcast-rs = "1.2.0"
hashbrown = "0.13.2"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["serde_derive"] }
thiserror = "1.0.38"
