[package]
name = "voxel-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
anyhow = "1.0.75"
bevy = {workspace = true}
bevy_rapier3d = "0.22.0"
bracket-noise = "0.8.7"
crossbeam = "0.8.2"
dashmap = "5.5.3"
derive_more = "0.99.17"
downcast-rs = "1.2.0"
hashbrown = "0.13.2"
noise = "0.8.2"
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
rand = "0.8.5"
rayon = "1.7.0"
serde = { version = "1.0.152", features = ["serde_derive"] }
smallvec = "1.11.1"
static_assertions = "1.1.0"
thiserror = "1.0.38"
